# headers and icon 
title: Ananya Sen
info: PhD Atmospheric Science @ UNR
icon-pic: assets/img/light.jpg

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
